name: Documentation
on:
  push:
    branches:
      - master
    paths:
      - 'docs/api/**.md'
      - 'docs/articles/**.md'
      - 'docs/apidoc/**.md'
      - 'docs/images/**'
      - 'docs/docfx.json'
      - 'docs/filterConfig.yml'
      - 'docs/index.md'
      - 'docs/toc.yml'
      - 'client/package.json'
      - 'server/package.json'
      - '!docs/build.*'
      - '!docs/.gitignore'
jobs:
  docs:
    name: Update documentation
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'Bump version') || contains(github.event.head_commit.message, 'Update documentation')"
    steps:
      - name: Dispatch event to altv-docs repo
        uses: peter-evans/repository-dispatch@v1.1.2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: altmp/altv-docs
          event-type: Update JS documentation
